export default () => [{ name: 'Alabama', abbreviation: 'AL', seen: false, seenBy: '' },
  { name: 'Alaska', abbreviation: 'AK', seen: false, seenBy: '' },
  { name: 'Arizona', abbreviation: 'AZ', seen: false, seenBy: '' },
  { name: 'Arkansas', abbreviation: 'AR', seen: false, seenBy: '' },
  { name: 'California',
    abbreviation: 'CA',
    seen: false,
    seenBy: '' },
  { name: 'Colorado', abbreviation: 'CO', seen: false, seenBy: '' },
  { name: 'Connecticut',
    abbreviation: 'CT',
    seen: false,
    seenBy: '' },
  { name: 'Delaware', abbreviation: 'DE', seen: false, seenBy: '' },
  { name: 'District Of Columbia',
    abbreviation: 'DC',
    seen: false,
    seenBy: '' },
  { name: 'Florida', abbreviation: 'FL', seen: false, seenBy: '' },
  { name: 'Georgia', abbreviation: 'GA', seen: false, seenBy: '' },
  { name: 'Hawaii', abbreviation: 'HI', seen: false, seenBy: '' },
  { name: 'Idaho', abbreviation: 'ID', seen: false, seenBy: '' },
  { name: 'Illinois', abbreviation: 'IL', seen: false, seenBy: '' },
  { name: 'Indiana', abbreviation: 'IN', seen: false, seenBy: '' },
  { name: 'Iowa', abbreviation: 'IA', seen: false, seenBy: '' },
  { name: 'Kansas', abbreviation: 'KS', seen: false, seenBy: '' },
  { name: 'Kentucky', abbreviation: 'KY', seen: false, seenBy: '' },
  { name: 'Louisiana', abbreviation: 'LA', seen: false, seenBy: '' },
  { name: 'Maine', abbreviation: 'ME', seen: false, seenBy: '' },
  { name: 'Maryland', abbreviation: 'MD', seen: false, seenBy: '' },
  { name: 'Massachusetts',
    abbreviation: 'MA',
    seen: false,
    seenBy: '' },
  { name: 'Michigan', abbreviation: 'MI', seen: false, seenBy: '' },
  { name: 'Minnesota', abbreviation: 'MN', seen: false, seenBy: '' },
  { name: 'Mississippi',
    abbreviation: 'MS',
    seen: false,
    seenBy: '' },
  { name: 'Missouri', abbreviation: 'MO', seen: false, seenBy: '' },
  { name: 'Montana', abbreviation: 'MT', seen: false, seenBy: '' },
  { name: 'Nebraska', abbreviation: 'NE', seen: false, seenBy: '' },
  { name: 'Nevada', abbreviation: 'NV', seen: false, seenBy: '' },
  { name: 'New Hampshire',
    abbreviation: 'NH',
    seen: false,
    seenBy: '' },
  { name: 'New Jersey',
    abbreviation: 'NJ',
    seen: false,
    seenBy: '' },
  { name: 'New Mexico',
    abbreviation: 'NM',
    seen: false,
    seenBy: '' },
  { name: 'New York', abbreviation: 'NY', seen: false, seenBy: '' },
  { name: 'North Carolina',
    abbreviation: 'NC',
    seen: false,
    seenBy: '' },
  { name: 'North Dakota',
    abbreviation: 'ND',
    seen: false,
    seenBy: '' },
  { name: 'Ohio', abbreviation: 'OH', seen: false, seenBy: '' },
  { name: 'Oklahoma', abbreviation: 'OK', seen: false, seenBy: '' },
  { name: 'Oregon', abbreviation: 'OR', seen: false, seenBy: '' },
  { name: 'Pennsylvania',
    abbreviation: 'PA',
    seen: false,
    seenBy: '' },
  { name: 'Rhode Island',
    abbreviation: 'RI',
    seen: false,
    seenBy: '' },
  { name: 'South Carolina',
    abbreviation: 'SC',
    seen: false,
    seenBy: '' },
  { name: 'South Dakota',
    abbreviation: 'SD',
    seen: false,
    seenBy: '' },
  { name: 'Tennessee', abbreviation: 'TN', seen: false, seenBy: '' },
  { name: 'Texas', abbreviation: 'TX', seen: false, seenBy: '' },
  { name: 'Utah', abbreviation: 'UT', seen: false, seenBy: '' },
  { name: 'Vermont', abbreviation: 'VT', seen: false, seenBy: '' },
  { name: 'Virginia', abbreviation: 'VA', seen: false, seenBy: '' },
  { name: 'Washington',
    abbreviation: 'WA',
    seen: false,
    seenBy: '' },
  { name: 'West Virginia',
    abbreviation: 'WV',
    seen: false,
    seenBy: '' },
  { name: 'Wisconsin', abbreviation: 'WI', seen: false, seenBy: '' },
  { name: 'Wyoming', abbreviation: 'WY', seen: false, seenBy: '' }];
