export default () => [
  { name: 'Alabama', seen: false, seenBy: '' },
  { name: 'Alaska', seen: false, seenBy: '' },
  { name: 'Arizona', seen: false, seenBy: '' },
  { name: 'Arkansas', seen: false, seenBy: '' },
  { name: 'California', seen: false, seenBy: '' },
  { name: 'Colorado', seen: false, seenBy: '' },
  { name: 'Connecticut', seen: false, seenBy: '' },
  { name: 'Delaware', seen: false, seenBy: '' },
  { name: 'District Of Columbia', seen: false, seenBy: '' },
  { name: 'Florida', seen: false, seenBy: '' },
  { name: 'Georgia', seen: false, seenBy: '' },
  { name: 'Hawaii', seen: false, seenBy: '' },
  { name: 'Idaho', seen: false, seenBy: '' },
  { name: 'Illinois', seen: false, seenBy: '' },
  { name: 'Indiana', seen: false, seenBy: '' },
  { name: 'Iowa', seen: false, seenBy: '' },
  { name: 'Kansas', seen: false, seenBy: '' },
  { name: 'Kentucky', seen: false, seenBy: '' },
  { name: 'Louisiana', seen: false, seenBy: '' },
  { name: 'Maine', seen: false, seenBy: '' },
  { name: 'Maryland', seen: false, seenBy: '' },
  { name: 'Massachusetts', seen: false, seenBy: '' },
  { name: 'Michigan', seen: false, seenBy: '' },
  { name: 'Minnesota', seen: false, seenBy: '' },
  { name: 'Mississippi', seen: false, seenBy: '' },
  { name: 'Missouri', seen: false, seenBy: '' },
  { name: 'Montana', seen: false, seenBy: '' },
  { name: 'Nebraska', seen: false, seenBy: '' },
  { name: 'Nevada', seen: false, seenBy: '' },
  { name: 'New Hampshire', seen: false, seenBy: '' },
  { name: 'New Jersey', seen: false, seenBy: '' },
  { name: 'New Mexico', seen: false, seenBy: '' },
  { name: 'New York', seen: false, seenBy: '' },
  { name: 'North Carolina', seen: false, seenBy: '' },
  { name: 'North Dakota', seen: false, seenBy: '' },
  { name: 'Ohio', seen: false, seenBy: '' },
  { name: 'Oklahoma', seen: false, seenBy: '' },
  { name: 'Oregon', seen: false, seenBy: '' },
  { name: 'Pennsylvania', seen: false, seenBy: '' },
  { name: 'Rhode Island', seen: false, seenBy: '' },
  { name: 'South Carolina', seen: false, seenBy: '' },
  { name: 'South Dakota', seen: false, seenBy: '' },
  { name: 'Tennessee', seen: false, seenBy: '' },
  { name: 'Texas', seen: false, seenBy: '' },
  { name: 'Utah', seen: false, seenBy: '' },
  { name: 'Vermont', seen: false, seenBy: '' },
  { name: 'Virginia', seen: false, seenBy: '' },
  { name: 'Washington', seen: false, seenBy: '' },
  { name: 'West Virginia', seen: false, seenBy: '' },
  { name: 'Wisconsin', seen: false, seenBy: '' },
  { name: 'Wyoming', seen: false, seenBy: '' }];
