export default () => [{ name: 'Alabama',
    abbreviation: 'AL',
    image: 'http://www.theus50.com/images/state-licenses/alabama-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Alaska',
    abbreviation: 'AK',
    image: 'http://www.theus50.com/images/state-licenses/alaska-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Arizona',
    abbreviation: 'AZ',
    image: 'http://www.theus50.com/images/state-licenses/arizona-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Arkansas',
    abbreviation: 'AR',
    image: 'http://www.theus50.com/images/state-licenses/arkansas-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'California',
    abbreviation: 'CA',
    image: 'http://www.theus50.com/images/state-licenses/california-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Colorado',
    abbreviation: 'CO',
    image: 'http://www.theus50.com/images/state-licenses/colorado-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Connecticut',
    abbreviation: 'CT',
    image: 'http://www.theus50.com/images/state-licenses/connecticut-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Delaware',
    abbreviation: 'DE',
    image: 'http://www.theus50.com/images/state-licenses/delaware-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'District Of Columbia',
    abbreviation: 'DC',
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/DC_2013.jpg',
    seenBy: '',
    seen: false },
  { name: 'Florida',
    abbreviation: 'FL',
    image: 'http://www.theus50.com/images/state-licenses/florida-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Georgia',
    abbreviation: 'GA',
    image: 'http://www.theus50.com/images/state-licenses/georgia-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Hawaii',
    abbreviation: 'HI',
    image: 'http://theus50.com/images/state-licenses/hawaii-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Idaho',
    abbreviation: 'ID',
    image: 'http://www.theus50.com/images/state-licenses/idaho-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Illinois',
    abbreviation: 'IL',
    image: 'http://www.theus50.com/images/state-licenses/illinois-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Indiana',
    abbreviation: 'IN',
    image: 'http://www.theus50.com/images/state-licenses/indiana-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Iowa',
    abbreviation: 'IA',
    image: 'http://www.theus50.com/images/state-licenses/iowa-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Kansas',
    abbreviation: 'KS',
    image: 'http://www.theus50.com/images/state-licenses/kansas-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Kentucky',
    abbreviation: 'KY',
    image: 'http://www.theus50.com/images/state-licenses/kentucky-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Louisiana',
    abbreviation: 'LA',
    image: 'http://www.theus50.com/images/state-licenses/louisiana-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Maine',
    abbreviation: 'ME',
    image: 'http://www.theus50.com/images/state-licenses/maine-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Maryland',
    abbreviation: 'MD',
    image: 'http://www.theus50.com/images/state-licenses/maryland-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Massachusetts',
    abbreviation: 'MA',
    image: 'http://www.theus50.com/images/state-licenses/massachusetts-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Michigan',
    abbreviation: 'MI',
    image: 'http://www.theus50.com/images/state-licenses/michigan-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Minnesota',
    abbreviation: 'MN',
    image: 'http://www.theus50.com/images/state-licenses/minnesota-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Mississippi',
    abbreviation: 'MS',
    image: 'http://www.theus50.com/images/state-licenses/mississippi-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Missouri',
    abbreviation: 'MO',
    image: 'http://www.theus50.com/images/state-licenses/missouri-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Montana',
    abbreviation: 'MT',
    image: 'http://www.theus50.com/images/state-licenses/montana-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Nebraska',
    abbreviation: 'NE',
    image: 'http://www.theus50.com/images/state-licenses/nebraska-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Nevada',
    abbreviation: 'NV',
    image: 'http://www.theus50.com/images/state-licenses/nevada-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'New Hampshire',
    abbreviation: 'NH',
    image: 'http://www.theus50.com/images/state-licenses/newhampshire-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'New Jersey',
    abbreviation: 'NJ',
    image: 'http://www.theus50.com/images/state-licenses/newjersey-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'New Mexico',
    abbreviation: 'NM',
    image: 'http://www.theus50.com/images/state-licenses/newmexico-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'New York',
    abbreviation: 'NY',
    image: 'http://www.theus50.com/images/state-licenses/newyork-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'North Carolina',
    abbreviation: 'NC',
    image: 'http://www.theus50.com/images/state-licenses/northcarolina-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'North Dakota',
    abbreviation: 'ND',
    image: 'http://www.theus50.com/images/state-licenses/northdakota-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Ohio',
    abbreviation: 'OH',
    image: 'http://www.theus50.com/images/state-licenses/ohio-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Oklahoma',
    abbreviation: 'OK',
    image: 'http://www.theus50.com/images/state-licenses/oklahoma-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Oregon',
    abbreviation: 'OR',
    image: 'http://www.theus50.com/images/state-licenses/oregon-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Pennsylvania',
    abbreviation: 'PA',
    image: 'http://www.theus50.com/images/state-licenses/pennsylvania-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Rhode Island',
    abbreviation: 'RI',
    image: 'http://www.theus50.com/images/state-licenses/rhodeisland-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'South Carolina',
    abbreviation: 'SC',
    image: 'http://www.theus50.com/images/state-licenses/southcarolina-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'South Dakota',
    abbreviation: 'SD',
    image: 'http://www.theus50.com/images/state-licenses/southdakota-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Tennessee',
    abbreviation: 'TN',
    image: 'http://www.theus50.com/images/state-licenses/tennessee-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Texas',
    abbreviation: 'TX',
    image: 'http://www.theus50.com/images/state-licenses/texas-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Utah',
    abbreviation: 'UT',
    image: 'http://www.theus50.com/images/state-licenses/utah-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Vermont',
    abbreviation: 'VT',
    image: 'http://www.theus50.com/images/state-licenses/vermont-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Virginia',
    abbreviation: 'VA',
    image: 'http://www.theus50.com/images/state-licenses/virginia-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Washington',
    abbreviation: 'WA',
    image: 'http://www.theus50.com/images/state-licenses/washington-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'West Virginia',
    abbreviation: 'WV',
    image: 'http://www.theus50.com/images/state-licenses/westvirginia-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Wisconsin',
    abbreviation: 'WI',
    image: 'http://www.theus50.com/images/state-licenses/wisconsin-license.jpg',
    seenBy: '',
    seen: false },
  { name: 'Wyoming',
    abbreviation: 'WY',
    image: 'http://www.theus50.com/images/state-licenses/wyoming-license.jpg',
    seenBy: '',
    seen: false }];
